### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#10]
This is an umbrella issue for all the translations we need for the site. 

We need:

- [ ] Translations for page texts in Finnish #30 
- [ ] Translations for page texts in Swedish #31 
- [x] Translations for event texts in Finnish
  - [x] Robotics sunday #32 
  - [x] Effective Python reading circle #35  
  - [x] Getting started in your tech career #37  
  - [x] Instabots and cybersecurity #39  
  - [x] Machine learning and mimosas! #41  
  - [x] Turku.py goes data science! #43  
  - [x] Robotics september #45 
- [ ] Translations for event texts in Swedish
  - [ ] Robotics sunday #33 
  - [ ] Effective Python reading circle #34 
  - [ ] Getting started in your tech career #36 
  - [ ] Instabots and cybersecurity #38 
  - [ ] Machine learning and mimosas! #40 
  - [ ] Turku.py goes data science! #42 
  - [ ] Robotics september #44 
See `docs/translations.md` for instructions how to create these translations

**Comment by MaximeKoitsalu** [comment]
Hey guys, if you still need help with the Swedish 🇸🇪 I'm happy to help!

**Comment by magdapoppins** [comment]
Hey @MaximeKoitsalu! Sure, feel free and you can tick those boxes as you go and make a pr for just adding Swedish or some part of it, that would be great! Hang in there until #16 is merged, though, so you have the files to translate separated. Should be all good to go in the beginning of next week! 😊
(Also, maybe it's a bit unnecessary to call us "guys", since we aren't guys.)

**Comment by MaximeKoitsalu** [comment]
Oops I'm sorry for that, bad habit! I've subscribed to notifications on #16 and I'll jump on it as soon as it's ready 👍!

**Comment by eevajonnapanula** [comment]
FYI @MaximeKoitsalu  - we are still in progress of updating the contribution guidelines and code of conduct, but [you can see them here](https://github.com/turkupy/turkupy.github.io/blob/feature/add-contributing-guidelines/CONTRIBUTING.md)

But other than that, the PR is merged so you can pick any of the tasks in this issue. I'm right now adding issues for every event translation, and will update them to this issue as soon as I have finished :)

**Comment by julienth37** [comment]
Hi,
I didn't see French on the list, I can translate from English to French, if it's something interesting tell me I could work on it.

**Comment by eevajonnapanula** [comment]
Hey @julienth37 and sorry for not answering before! We chose finnish and swedish to the list, because they are the languages used in Turku (as this is a website for a local meetup). Thanks for offering, though
